# Generated by Django 4.0.6 on 2022-09-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_attendance_date_alter_attendance_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
